### PR TITLE
Adding a few pip requirements I needed to get autogguf to run successfully

### PR DESCRIPTION
**Pull request by bigattichouse**
I think these requirements were needed in the llama.cpp make/compilation stage.

### CODE REVIEW

**Comment by monk1337** [comment]
Thank you for your contribution! Let's create a separate file called 'external_dependencies.txt' to keep track of any future requirements that may arise. This way, we can easily add new dependencies to this file whenever needed, keeping our main requirements file clean and focused on the core dependencies.

**Comment by bigattichouse** [comment]
Undestood. Also, I noticed that llama.cpp, though checked out doesn't get `make`d on a bare run.

Perhaps a `install_external_dependencies.sh` instead of a text file?

**Comment by monk1337** [comment]
> Undestood. Also, I noticed that llama.cpp, though checked out doesn't get `make`d on a bare run.
> 
> Perhaps a `install_external_dependencies.sh` instead of a text file?

We can run the external_dependencies.txt from the `autogguf.sh` file like this

```pip3 install -r external_dependencies.txt```

**Comment by bigattichouse** [comment]
Oh, yeah. that's good.

One more thing:  putting a `make` call in the llama.cpp section "assume make" wouldn't cost much for compute time, and I end up having to do it each time (for some reason).  I've been nuking and recloning my local and running from scratch each time. You cool if I put the make call in there?

**Comment by monk1337** [comment]
> Oh, yeah. that's good.
> 
> One more thing: putting a `make` call in the llama.cpp section "assume make" wouldn't cost much for compute time, and I end up having to do it each time (for some reason). I've been nuking and recloning my local and running from scratch each time. You cool if I put the make call in there?

I was tying to avoid the `make` time for llama.cpp as it takes some time but if  [ doesn't get maked on a bare run. ] that's the case then we can put `make` there.

**Comment by bigattichouse** [comment]
I'll start over, using the `external_dependencies.txt` and see why the make you run the first time doesn't seem to create quantize.. maybe running the pip step before the make.  I pulled my change request so I can start over.

**Comment by monk1337** [comment]
> I'll start over, using the `external_dependencies.txt` and see why the make you run the first time doesn't seem to create quantize.. maybe running the pip step before the make. I pulled my change request so I can start over.

Sure!!

**Pull request closed without merging**
